services:
  backend-service:
    image: backend
    ports:
      - 8000:8000
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=postgres
    depends_on:
      - db
  frontend-service:
    image: frontend
    ports:
      - 5000:5000
    container_name: frontend
      
  redis-service:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: postgres
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: nginx
    depends_on:
      - backend-service
      - frontend-service

